In [1]:
import pandas as pd

In [ ]:
data_presentados = pd.read_excel("../../data/raw/presentados/Expedientes Presentados 2017.xlsx")
data_resueltos = pd.read_excel("../../data/raw/resueltos/Expedientes Resueltos 2017.xlsx")

In [11]:
data_resueltos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3208 entries, 0 to 3207
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   NRO. DE EXPEDIENTE     3208 non-null   object
 1   EXPEDIENTE DE ORIGEN   3208 non-null   object
 2   TIPO DE EXPEDIENTE     3208 non-null   object
 3   FECHA DE PRESENTACIÓN  3208 non-null   datetime64[ns]
 4   DENUNCIADOS            3000 non-null   object
 5   MATERIA SPC            2489 non-null   object
 6   F. RESOLUCIÓN          3208 non-null   datetime64[ns]
 7   NRO. DE RESOLUCIÓN     3208 non-null   object
 8   FORMA DE CONCLUSIÓN    3208 non-null   object
dtypes: datetime64[ns](2), object(7)
memory usage: 225.7+ KB

In [13]:
data_presentados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 7 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   INGRESO EN SALA                           2930 non-null   object
 1   NRO. EXPEDIENTE ORIGEN                    2924 non-null   object
 2   TIPO EXPEDIENTE                           2930 non-null   object
 3   FECHA DE PRESENTACION                     2930 non-null   datetime64[ns]
 4   DENUNCIADO(S)                             2805 non-null   object
 5   TIPO Y NUMERO DE DOCUMENTO DENUNCIADO(S)  2799 non-null   object
 6   MATERIA                                   2275 non-null   object
dtypes: datetime64[ns](1), object(6)
memory usage: 160.4+ KB

In [14]:
data_presentados.head()

,INGRESO EN SALA,NRO. EXPEDIENTE ORIGEN,TIPO EXPEDIENTE,FECHA DE PRESENTACION,DENUNCIADO(S),TIPO Y NUMERO DE DOCUMENTO DENUNCIADO(S),MATERIA
0,0001-2017/SPC-QUEJA,0237-2016/CPC-INDECOPI-PIU,QUEJA,2017-01-02,COMISION DE LA OFICINA REGIONAL DEL INDECOPI D...,RUC : 20133840533,NaN
1,0002-2017/SPC-QUEJA,0312-2015/CPC-INDECOPI-AQP,QUEJA,2017-01-03,COMISION DE LA OFICINA REGIONAL DEL INDECOPI D...,RUC : 20133840533,NaN
2,0003-2017/SPC-APELACION,0147-2016/CPC-INDECOPI-LAM,APELACION,2017-01-02,TOURS ANGEL DIVINO S.A.C,RUC : 20395419715,TRANSPORTE DE PASAJEROS
3,0004-2017/SPC-APELACION,0121-2016/CPC-INDECOPI-LAM,APELACION,2017-01-02,UNIVERSIDAD PARTICULAR DE CHICLAYO,RUC : 20209239541,SERVICIOS DE ENSEÑANZA
4,0005-2017/SPC-APELACION,0033-2015/CPC-INDECOPI-LAM,APELACION,2017-01-02,UNIVERSIDAD PARTICULAR DE CHICLAYO,RUC : 20209239541,SERVICIOS DE ENSEÑANZA

In [15]:
data_resueltos.head()

,NRO. DE EXPEDIENTE,EXPEDIENTE DE ORIGEN,TIPO DE EXPEDIENTE,FECHA DE PRESENTACIÓN,DENUNCIADOS,MATERIA SPC,F. RESOLUCIÓN,NRO. DE RESOLUCIÓN,FORMA DE CONCLUSIÓN
0,2624-2016/SPC-APELACION,1000-2014/CC1,APELACION,2016-07-12,SCOTIABANK PERÚ S.A.A.,SERVICIOS BANCARIOS. OTROS,2017-01-02,00000001-2017/SPC,>>NULIDAD
1,2626-2016/SPC-APELACION,0080-2015/CC1,APELACION,2016-07-12,BANCO INTERNACIONAL DEL PERÚ S.A.A. - INTERBANK,SERVICIOS BANCARIOS. OTROS,2017-01-02,00000002-2017/SPC,>>CONFIRMA
2,2657-2016/SPC-APELACION,1352-2015/CC1,APELACION,2016-07-14,BANCO INTERAMERICANO DE FINANZAS S.A.,SERVICIOS BANCARIOS. INFORMACION,2017-01-02,00000003-2017/SPC,>>CONFIRMA
3,2658-2016/SPC-APELACION,1409-2015/CC1,APELACION,2016-07-14,SCOTIABANK PERÚ S.A.A.,SERVICIOS BANCARIOS. INFORMACION,2017-01-02,00000004-2017/SPC,>>CONFIRMA
4,2711-2016/SPC-APELACION,0387-2015/CPC-INDECOPI-AQP,APELACION,2016-07-19,BANCO INTERNACIONAL DEL PERÚ S.A.A.- INTERBANK,SERVICIOS BANCARIOS. OTROS,2017-01-02,00000005-2017/SPC,>>CONFIRMA