In [10]:
import polars as pl
import pandas as pd

In [11]:
# leer los archivos para la revision

data_s = pd.read_csv("../../data/synthetic/expedientes_synthetic.csv")
data_c = pd.read_csv("../../data/clean/expedientes_clean.csv")

In [13]:
# informacion general de los datos
data_s.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 969245 entries, 0 to 969244
Data columns (total 18 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   DENUNCIADOS_pres         969245 non-null  object
 1   DOC_DENUNCIADO           965126 non-null  object
 2   EXPEDIENTE_ORIGEN_pres   967500 non-null  object
 3   FECHA_PRESENTACION_pres  969245 non-null  object
 4   FECHA_RESOLUCION         921454 non-null  object
 5   FORMA_CONCLUSION         921454 non-null  object
 6   MATERIA_pres             798513 non-null  object
 7   NRO_EXPEDIENTE           969245 non-null  object
 8   NRO_RESOLUCION           921454 non-null  object
 9   RES_MATCH_SOURCE         969245 non-null  object
 10  TIPO_EXPEDIENTE_pres     969245 non-null  object
 11  año_pres                 969245 non-null  int64
 12  año_res                  921454 non-null  float64
 13  TIMESTAMP                969245 non-null  object
 14  DETALLE_QUEJA            969245 non-null  object
 15  ES_SPAM                  969245 non-null  int64
 16  SPAM_TAGS                176708 non-null  object
 17  SPAM_SCORE               969245 non-null  float64
dtypes: float64(2), int64(2), object(14)
memory usage: 133.1+ MB

In [14]:
data_c.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14231 entries, 0 to 14230
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   NRO_EXPEDIENTE           14231 non-null  object
 1   EXPEDIENTE_ORIGEN_pres   14206 non-null  object
 2   TIPO_EXPEDIENTE_pres     14231 non-null  object
 3   FECHA_PRESENTACION_pres  14231 non-null  object
 4   DENUNCIADOS_pres         13759 non-null  object
 5   DOC_DENUNCIADO           13746 non-null  object
 6   MATERIA_pres             11774 non-null  object
 7   año_pres                 14231 non-null  int64
 8   FECHA_RESOLUCION         13543 non-null  object
 9   NRO_RESOLUCION           13543 non-null  object
 10  FORMA_CONCLUSION         13543 non-null  object
 11  año_res                  13543 non-null  float64
 12  RES_MATCH_SOURCE         14231 non-null  object
dtypes: float64(1), int64(1), object(11)
memory usage: 1.4+ MB

In [17]:
# Vista inicial
data_s.sample(5)

,DENUNCIADOS_pres,DOC_DENUNCIADO,EXPEDIENTE_ORIGEN_pres,FECHA_PRESENTACION_pres,FECHA_RESOLUCION,FORMA_CONCLUSION,MATERIA_pres,NRO_EXPEDIENTE,NRO_RESOLUCION,RES_MATCH_SOURCE,TIPO_EXPEDIENTE_pres,año_pres,año_res,TIMESTAMP,DETALLE_QUEJA,ES_SPAM,SPAM_TAGS,SPAM_SCORE
284722,SALA ESPECIALIZADA EN PROCEDIMIENTOS CONCURSALES,20133840533,NaN,2017-12-05,2017-12-13,INFUNDADA,NaN,2710-2017/SPC-QUEJA,00003478-2017/SPC,nro,QUEJA,2017,2017.0,2017-12-05 12:42:48,Quiero reportar un problema contra SALA ESPECI...,0,NaN,0.04
370328,AUTOVENTAS GRAN PRIX SRL,20393579413,0102-2019/CPC-INDECOPI-LOR,2021-01-05,2021-05-27,CONSENTIDO,VENTA DE VEHICULOS AUTOMOTORES Y MOTOCICLETAS,0015-2021/SPC-APELACION,00001198-2021/SPC,nro,APELACION,2021,2021.0,2021-01-05 08:00:29,Presento una queja contra AUTOVENTAS GRAN PRIX...,0,NaN,0.03
447681,COMISION DE PROTECCION AL CONSUMIDOR 3,20133840533,0135-2019/CC3-SIA,2020-09-24,2020-10-01,FUNDADA,NaN,1150-2020/SPC-QUEJA,00001730-2020/SPC,nro,QUEJA,2020,2020.0,2020-09-24 10:31:42,Deseo registrar una denuncia contra COMISION D...,0,NaN,0.09
623043,IBERIA LINEAS AEREAS DE ESPANA SOCIEDAD ANONIM...,20100041449,0409-2020/CC2,2021-06-16,2021-12-06,NULIDAD,TRANSPORTE DE PASAJEROS,1203-2021/SPC-APELACION,00002621-2021/SPC,nro,APELACION,2021,2021.0,2021-06-16 02:10:00,Quiero reportar un problema contra IBERIA LINE...,1,night_activity,0.88
348768,MAPFRE PERU COMPANIA DE SEGUROS Y REASEGUROS S...,20100043140 / RUC : 20202380621,0055-2019/CC1,2019-06-25,2019-11-27,CONFIRMA,CREDITO DE CONSUMO /SEGURO VEHICULAR,1701-2019/SPC-APELACION,00003357-2019/SPC,nro,APELACION,2019,2019.0,2019-06-25 12:59:03,Interpongo un reclamo contra MAPFRE PERU COMPA...,0,NaN,0.04

### Chiqui liempieza de la data sintetica

In [25]:
# Eliminar las filas sin valor

## Eiminar las columnas año_res y año_pres
data_s = data_s.drop(columns=["año_pres", "año_res"])

## Eliminar columan RES_MATCH_SOURCE generada en el merge
data_s = data_s.drop(columns=["RES_MATCH_SOURCE"])

In [30]:
# Cambiar nombres de columnas para facilitar la comprencion
data_s = data_s.rename(columns={
    "DENUNCIADOS_pres": "DENUNCIADOS",
    "TIPO_EXPEDIENTE_pres": "TIPO_EXPEDIENTE",
    "MATERIA_pres":"MATERIA",
    "FECHA_PRESENTACION_pres":"FECHA_PRESENTACION",
})

In [31]:
# reemplazar el csv sintetico con el limpio
data_s.to_csv("../../data/synthetic/expedientes_synthetic.csv", index=False)

In [32]:
data_s.sample(5)

,DENUNCIADOS,DOC_DENUNCIADO,EXPEDIENTE_ORIGEN_pres,FECHA_PRESENTACION,FECHA_RESOLUCION,FORMA_CONCLUSION,MATERIA,NRO_EXPEDIENTE,NRO_RESOLUCION,TIPO_EXPEDIENTE,TIMESTAMP,DETALLE_QUEJA,ES_SPAM,SPAM_TAGS,SPAM_SCORE
209492,TRANSPORTES EL PINO SAC,20502324927,0183-2019/CC3-SIA,2020-09-30,2020-11-24,CONFIRMA,TRANSPORTE DE PASAJEROS,1180-2020/SPC-APELACION,00002187-2020/SPC,APELACION,2020-09-30 09:40:46,Presento una queja contra TRANSPORTES EL PINO ...,0,NaN,0.26
922812,BANCO DE CREDITO DEL PERU,20100047218,0747-2019/CC1,2020-01-10,2020-02-10,CONSENTIDO,PRESTAMO PERSONAL,0050-2020/SPC-APELACION,00000379-2020/SPC,APELACION,2020-01-10 09:00:58,Quiero reportar un problema contra BANCO DE CR...,0,NaN,0.27
230860,FINANCIERA OH! SA O FINANCIERA OH SA,20522291201,0252-2020/CC1,2021-05-17,2021-08-04,CONSENTIDO,TARJETA DE CREDITO,0997-2021/SPC-APELACION,00001731-2021/SPC,APELACION,2021-05-17 14:13:24,Deseo registrar una denuncia contra FINANCIERA...,0,NaN,0.27
655428,BANCO INTERAMERICANO DE FINANZAS,20101036813,0074-2017/CPC-INDECOPI-AQP,2017-11-07,2018-04-23,CONFIRMA,CUENTA DE AHORROS,2413-2017/SPC-APELACION,00000870-2018/SPC,APELACION,2017-11-07 08:50:18,PRESENTO UNA QUEJA CONTRA BANCO INTERAMERICANO...,1,duplicate_text;duplicate_text;temporal_burst,0.79
286265,AUTOMOTORES GILDEMEISTER-PERU SA,20506006024,0073-2017/ILN-CPC,2017-12-27,2018-06-20,CONFIRMA,VENTA DE VEHICULOS AUTOMOTORES Y MOTOCICLETAS,2905-2017/SPC-APELACION,00001517-2018/SPC,APELACION,2017-12-27 14:23:40,Presento una queja contra AUTOMOTORES GILDEMEI...,0,NaN,0.12

In [33]:
data_s.sample(5)

,DENUNCIADOS,DOC_DENUNCIADO,EXPEDIENTE_ORIGEN_pres,FECHA_PRESENTACION,FECHA_RESOLUCION,FORMA_CONCLUSION,MATERIA,NRO_EXPEDIENTE,NRO_RESOLUCION,TIPO_EXPEDIENTE,TIMESTAMP,DETALLE_QUEJA,ES_SPAM,SPAM_TAGS,SPAM_SCORE
73450,BANCO DE CREDITO DEL PERU,20100047218,0204-2019/CPC-INDECOPI-LAL,2020-12-21,2021-06-02,NULIDAD E INTEGRACION : FUNDADA,CUENTA DE AHORROS,1963-2020/SPC-APELACION,00001234-2021/SPC,APELACION,2020-12-21 00:29:34,Presento una queja contra BANCO DE CREDITO DEL...,0,NaN,0.22
181180,MAPFRE PERU COMPANIA DE SEGUROS Y REASEGUROS SA,20202380621,0592-2017/CC1,2018-03-09,2018-09-03,CONFIRMA,SEGURO VEHICULAR,0749-2018/SPC-APELACION,00002257-2018/SPC,APELACION,2018-03-09 14:36:35,Interpongo un reclamo contra MAPFRE PERU COMPA...,0,NaN,0.06
944844,CENCOSUD RETAIL PERU SA,20109072177,0137-2019/CPC-INDECOPI-AQP,2020-10-15,2020-11-19,CONSENTIDO,VENTA DE ABARROTES,1318-2020/SPC-APELACION,00002150-2020/SPC,APELACION,2020-10-15 12:32:49,QUIERO REPORTAR UN PROBLEMA CONTRA CENCOSUD RE...,0,NaN,0.20
780991,SCOTIABANK PERU SAA,20100043140,0751-2018/CC1,2018-11-19,2019-04-29,CONFIRMA,TARJETA DE CREDITO,3086-2018/SPC-APELACION,00001109-2019/SPC,APELACION,2018-11-19 07:54:43,Presento una queja contra SCOTIABANK PERU SAA ...,0,NaN,0.16
470729,Grupo Comercial SAC,20263827776,0954-2020/CC2,2021-09-29,2021-10-20,NULIDAD E INTEGRACION : IMPROCEDENTE,SERVICIOS DE ENSEÑANZA,2075-2021/SPC-APELACION,00002316-2021/SPC,APELACION,2021-09-29 02:10:00,Deseo registrar una denuncia contra CENTRO EDU...,1,night_activity;fake_entity;temporal_burst,0.85